### ISSUE TITLE
How start and stop with javascript?

### ISSUE THREAD

**Issue by StoricU** [raschy/ioBroker.solarmanpv#121]
Hi,

I'm trying to start and stop this adapter on sunrise and sunset, but having some issues.
`// Start an adapter instance at sunrise
schedule({astro: "sunrise"}, function () {
    setState("system.adapter.solarmanpv.0.enabled", true); 
});

// Stop an adapter instance at sunset
schedule({astro: "sunset"}, function () {
    setState("system.adapter.solarmanpv.0.enabled", false); 
});
`
Is there another state that will do what I want?

**Comment by raschy** [comment]
If you really want the adapter to be stopped/started by a Javascript, you can use this sequence:
````
const obj = getObject("system.adapter.solarmanpv.0");
obj.common.enabled = false;     // Adapter ausschalten
//obj.common.enabled = true;      // Adapter einschalten
setObject("system.adapter.solarmanpv.0", obj);
````
