### ISSUE TITLE
Question: Would it be possbile to get the data directly from the logger of the inverter?

### ISSUE THREAD

**Issue by der1sebi** [raschy/ioBroker.solarmanpv#13]
To avoid the cloud from the solarman app and bringing my information to a China cloud it would be great to get the data directly from the inverter. Have you planned something like this for future updates?

**Comment by raschy** [comment]
I am trying to read out the inverter directly in various ways. So far I have not really been successful.

**Comment by der1sebi** [comment]
Thats great to hear. Normally it should be similar to the steps youre using now I guess?!

**Comment by der1sebi** [comment]
Have found this topic on FHEM. Maybe it will help you?
https://forum.fhem.de/index.php/topic,123506.0.html

**Comment by der1sebi** [comment]
And maybe this one will be very interesting for you as well:
https://github.com/dr-ni/mi600

**Comment by raschy** [comment]
Many thanks for the tips. I have already studied the articles and a few others, but have not yet come to a satisfactory conclusion.

**Comment by der1sebi** [comment]
Thanks for your effort. I really appreciate it.

**Comment by raschy** [comment]
After extensive research, the implementation of the local readout is not quite trivial. On the other hand, this would be a completely different project than this one. Therefore, this issue is closed.
