### ISSUE TITLE
Change to new API

### ISSUE THREAD

**Issue by ScumbagSteve** [raschy/ioBroker.solarmanpv#139]
I have received the following information via mail. Please consider changing to new API.

Dear valued user,

In order to provide you with a better experience, SOLARMAN will upgrade data centers from 2024-01-15 09:00 to 2024-01-15 17:00 (UTC+8). During the upgrade, OPENAPI service will be unavailable.

After the upgrade, please use the new OPENAPI domain https://globalapi.solarmanpv.com to replace previous domain https://api.solarmanpv.com . Your APPID and APPSECRET will remain the same, but you will need to request for a new token to access all your data under SOLARMAN account.

If you need historical data during the upgrade, we recommend that you use the historical data API (API 3.4 and API 4.3) to supplement it after the upgrade is completed.

Should you have any questions or concerns, please do not hesitate to contact us at customerservice@solarmanpv.com.

Thank you for choosing SOLARMAN platform, and we look forward to providing you with an even better user experience.

Sincerely,

The SOLARMAN Team

**Comment by raschy** [comment]
I have also received this information, but I don't know what is supposed to happen on the deadline. The transfer to the specified domain already took place in April 2023. I may receive further information.
