### ISSUE TITLE
B_Pdcg1 (Akku lade/entlade Leistung) wird nicht mehr aktualisiert

### ISSUE THREAD

**Issue by ltspicer** [raschy/ioBroker.solarmanpv#157]
B_Pdcg1 (Akku lade/entlade Leistung) wird seit heute Morgen 4:00 Uhr nicht mehr aktualisiert.
Die anderen Datenpunkte funktionieren normal.

Habt ihr das Problem auch?
Ist das nur ein vorübergehendes Problem oder sendet der Solarman Server diesen Wert unter einem anderen Namen?

**Versions:**  
 - Adapter version: v0.5.1
 - JS-Controller version: 5.0.19
 - Node version: v18.20.2
 - Operating system: Debian Bullseye (on Raspberry)

**Comment by raschy** [comment]
Wenn Solarman Werte ändert, sollten sie bei Eintreffen eines gültigen Wertes diesem mit dem 'neuen' Namen im Objektbaum anlegen. (Ist nicht von der Hand zu weisen, weil es in der Vergangenheit auch schon mal Typänderungen gab. So wurde aus einem numerischen Wert ein String. Das muss allerdings manuel angepasst werden.) Ich selbst habe keinen Akku und kann daher zum Grundproblem nichts sagen.

**Comment by ltspicer** [comment]
Würde sich das Änderungsdatum nicht ändern, wenn plötzlich ein String anstelle eines numerischen Wertes daher kommt?
![Auswahl_001](https://github.com/raschy/ioBroker.solarmanpv/assets/11616336/b2687d11-8168-4476-a8d4-db2c0654a016)

**Comment by ltspicer** [comment]
Wirklich merkwürdig. Die meisten anderen Daten kommen an.
Auf der Handy-App kommen die aktuellen Akku-Daten auch an.
Hier nochmal ein Screenshot.

![Auswahl_001](https://github.com/raschy/ioBroker.solarmanpv/assets/11616336/272435c7-cc62-4030-ae24-431d05c7321a)

Irgend ein Tipp zum debuggen?

**Comment by raschy** [comment]
Wenn neue Daten kommen, ändert sich natürlich auch das Datum. Da alle anderen Werte kommen würde ich mal bis morgen warten, je nachdem, was mit dem Akku so passiert.

**Comment by ltspicer** [comment]
Leider unverändert.
Ist hier niemand, der auch ein Akku hat?
Wenn ja, bitte mal nachschauen, ob der B_Pdcg1 sich aktualisiert.

**Comment by ltspicer** [comment]
Kann es sein, dass der **B_Pdcg1** durch **B_P1** abgelöst wurde?

![Auswahl_001](https://github.com/raschy/ioBroker.solarmanpv/assets/11616336/aec15dd5-449d-4c20-9932-3d1f3afbd478)

**Comment by raschy** [comment]
Nichts ist unmöglich! Wie gesagt, ich habe keinen Akku und kann daher nichts dazu sagen. Bitte beobachten und berichten.

**Comment by ltspicer** [comment]
Bis jetzt sieht es so aus, dass neu wirklich **B_P1** der gewünschte Datenpunkt ist. **B_Pdcg1** ist verwaist.
Mit dieser Erkenntnis schliesse ich dieses Issue mal ;)
