### ISSUE TITLE
No data since 11.07.2024 9:35h

### ISSUE THREAD

**Issue by unstressable** [raschy/ioBroker.solarmanpv#171]
Nothing changed, log says:
<html>
<body>

solarmanpv.0 | 2024-07-15 20:21:20.690 | warn | [initializeStation] error: undefined
-- | -- | -- | --

</body>
</html>

Adapter 0.5.1

ioBroker latest

**Comment by raschy** [comment]
It looks like Solarman has changed their regulations and are actively seeking approval for the new developer regulations.
Please write to Solarman support. They will then reply with an appropriate reply form.

**Comment by unstressable** [comment]
I wrote them, but no helpful answer.
They told me, that they changed the API System, but they did not tell how to fix the problem.

**Comment by raschy** [comment]
The dialog with Solarman Support seems to be a little bit slow.  
See also: https://forum.iobroker.net/topic/55799/solarman-pv-bosswerk-mi-deye/554

**Comment by unstressable** [comment]
I switched to the "deyeidc" Adapter. This one seem to work actally.
it seems to collect data locally. This is much better than via cloud.

**Comment by raschy** [comment]
Thank you for your feedback. Have fun.
