### ISSUE TITLE
Adapter doesn't log in and terminates with unspecified error

### ISSUE THREAD

**Issue by Brunnengustel** [raschy/ioBroker.solarmanpv#189]
**Describe the bug**  
Adapter stopped working a long time ago. Before it had worked fine. Solarman has confirmed, that my credentials are correct (they weren't changed).

**To Reproduce**  
1. Restart Adapter
2. Check Protocol
3. See: Error

**Expected behavior**  
Login, commence getting current values

**Screenshots & Logfiles**  
solarmanpv.0 | 2024-09-22 09:30:06.702 | debug | [callback] cleaned everything up...
-- | -- | -- | --
solarmanpv.0 | 2024-09-22 09:30:06.196 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Everything done. Going to terminate till next schedule
solarmanpv.0 | 2024-09-22 09:30:06.196 | debug | [onReady] finished - stopping instance
solarmanpv.0 | 2024-09-22 09:30:06.196 | debug | [main] catch "could not retrieve token."
solarmanpv.0 | 2024-09-22 09:30:06.195 | warn | [initializeStation] error: undefined
solarmanpv.0 | 2024-09-22 09:30:04.609 | debug | [checkUserData] Crc 382b2a9363c59bca25a44469afee6ac4
solarmanpv.0 | 2024-09-22 09:30:04.604 | debug | [onReady] started: solarmanpv.0
solarmanpv.0 | 2024-09-22 09:30:04.597 | info | starting. Version 0.6.1 in D:/ioBroker/node_modules/iobroker.solarmanpv, node: v18.16.0, js-controller: 5.0.19

**Comment by raschy** [comment]
This effect occurs from time to time. See also the forum: 
https://forum.iobroker.net/topic/55799/solarman-pv-bosswerk-mi-deye/548

It may help to log in again on the Solarman website so that the account is woken up again. 
Otherwise, see also #171.
