### ISSUE TITLE
Doppelte Log-Einträge

### ISSUE THREAD

**Issue by unstressable** [raschy/ioBroker.solarmanpv#33]
Folgende Einträge erscheinen doppelt im Log:

`<html>
<body>

solarmanpv.0 | 2022-11-09 15:36:04.952 | error | [onReady] error: AxiosError: timeout of 2000ms exceeded
-- | -- | -- | --
solarmanpv.0 | 2022-11-09 15:36:04.948 | warn | [initializeStation] error: AxiosError: timeout of 2000ms exceeded
solarmanpv.0 | 2022-11-09 15:00:08.947 | error | [onReady] error: AxiosError: timeout of 2000ms exceeded
solarmanpv.0 | 2022-11-09 15:00:08.944 | warn | [initializeStation] error: AxiosError: timeout of 2000ms exceeded
solarmanpv.0 | 2022-11-09 14:54:06.228 | error | [onReady] error: AxiosError: timeout of 2000ms exceeded
solarmanpv.0 | 2022-11-09 14:54:06.222 | warn | [initializeStation] error: AxiosError: timeout of 2000ms exceeded

</body>
</html>`

**Comment by raschy** [comment]
Welche Version läuft da?

**Comment by unstressable** [comment]
> Welche Version läuft da?

0.1.2

OK, sehe gerade, dass es schon 0.2.0 gibt. Gibts die auch auf NPM, oder nur Github?

**Comment by raschy** [comment]
Gibt es im iobroker-Repository im latest. node.js 16.x sollte installiert sein.

**Comment by unstressable** [comment]
> Gibt es im iobroker-Repository im latest. node.js 16.x sollte installiert sein.

muss ich  da meinen Adapter zuerst deinstallieren?
<img width="844" alt="image" src="https://user-images.githubusercontent.com/50423935/201176072-2f48d792-25a9-4755-8184-df66ef99d9fe.png">

**Comment by raschy** [comment]
Das wäre am sinnvollsten. Alles Alte raus und dann die Version 0.2.0 aus dem Latest installieren. Anschließend die Credentials eingeben, dann sollte der Adapter laufen.

**Comment by unstressable** [comment]
> Das wäre am sinnvollsten. Alles Alte raus und dann die Version 0.2.0 aus dem Latest installieren. Anschließend die Credentials eingeben, dann sollte der Adapter laufen.

ok, werde ich probieren. Aktuell wird mir der Adapter nicht im ioBroker angeboten, kann aber vielleicht daran liegen, dass ich ihn damals von github installiert hatte.

**Comment by raschy** [comment]
Ist auch das richtige Repository ausgewählt? > http://iobroker.live/repo/sources-dist-latest.json

**Comment by unstressable** [comment]
Bei mir war die Stable drin:
http://download.iobroker.net/sources-dist.json

hab nun die latest hinzugefügt :
http://iobroker.live/repo/sources-dist-latest.json
und aktiviert, dann fand ich den Adapter.

Bin jetzt auf V0.2.0

Wieso ist er nicht im Stable drin?

**Comment by raschy** [comment]
Nach welchen Kriterien der Adapter ins Stable kommt ist mir (noch) nicht bekannt. Wichtiger zu wissen wäre jetzt, ob der Adapter läuft!

**Comment by unstressable** [comment]
Läuft nun, wenn wieder Fehler kommen, melde ich mich nochmal.
