### ISSUE TITLE
Feature Request: Disable Auto-Refresh while sun is down

### ISSUE THREAD

**Issue by unstressable** [raschy/ioBroker.solarmanpv#34]
Would be nice to have a funktion to disable the Adapter after sunset and before sunrise to save machine power.

**Comment by raschy** [comment]
Do you really think that turning off a scheduled adapter will save energy?

**Comment by unstressable** [comment]
I think about computing power and a clean log (Axios error; timeout)

**Comment by raschy** [comment]
I'll look at the development effort and any negative side effects. In the adapter, sunrise and sunset must still be calculated, which does not have much to do with the readout of the cloud. Therefore probably not.

**Comment by unstressable** [comment]
Just provide us an Object to disable the data fetch, then we could do the rest over a Java/Blockly Script.
The adapter by itself does not have to be disabled.

**Comment by raschy** [comment]
This object (obj.common.enabled = status; // enable/disable adapter) is built into every adapter by default. Every user is free to turn the adapter off and on again with a script as he or she sees fit.

**Comment by unstressable** [comment]
I did it via Blockly:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/50423935/203162005-0000e5f5-5c1d-40c8-bbfe-ca679fe5b8d4.png">
