### ISSUE TITLE
Installation geht nicht weiter

### ISSUE THREAD

**Issue by fr00sch** [raschy/ioBroker.solarmanpv#4]
Hey raschy,

vorab schonmal vielen Dank für den Adapter, leider war es zu Anfang etwas schwer den Adapter zu finden:
Der Adapter wird in dem Menü als "undefined" dargestellt:
![grafik](https://user-images.githubusercontent.com/51095725/175544842-2ad6acce-45a5-444f-9c36-732916d5658f.png)

Dann bleibt leider die Installation hier stehen und es gibt keine Infos über die Debug-Schnittstelle:
<html><body>

host.iobroker | 2022-06-24 15:18:14.212 | info | iobroker Installing raschy/ioBroker.solarmanpv... (System call)
-- | -- | -- | --
host.iobroker | 2022-06-24 15:18:14.211 | info | iobroker NPM version: 6.14.17
host.iobroker | 2022-06-24 15:18:14.004 | info | iobroker install raschy/ioBroker.solarmanpv
host.iobroker | 2022-06-24 15:18:13.390 | info | iobroker url raschy/ioBroker.solarmanpv --host iobroker

</body>
</html>

Meine Versionen sind:
Node.js v14.19.3 (Empfohlene Version v16.15.1)
NPM    6.14.17
iobroker-Version: 4.0.23

Gruß fr00sch

**Comment by raschy** [comment]
Hi fr00sch, ich hatte vergessen zu erwähnen, dass für diesen Adapter der Admin 5 Vorraussetzung ist. Kannst du upgraden und nochmal versuchen? Ich habe den Adapter auch via 'Benutzerdefiniert' installliert.

**Comment by fr00sch** [comment]
Hey, ich habe sogar schon die Admin 6.1.4 und kann auch leider nicht mehr zurück.

**Comment by Ilovegym66** [comment]
@fr00sch update mal auf die vorgeschlagene Node und NPM Version und versuche dann eine Installation mit einer funktionierenden Admin Version ( 6.1.2 etc, keine 6.1.4 ) nochmal.. :-)

**Comment by raschy** [comment]
@fr00sch Ist denn der Adapter schon/trotzdem sichtbar? Ich hatte in einem älteren Testsystem auch so einen Effekt. Die Installation des Adapters blieb hängen, aber ich konnte auch bei nodejs 4.19.1, npm 6.14.16 und Admin v5.3.8 eine Instanz hinzufügen. Dann die richtigen Parameter und dann müsste es laufen.

**Comment by fr00sch** [comment]
@raschy 
Mit einem Update bin ich schon ein paar Schritte weiter gekommen:
Node.js: v16.16.0
NPM: v8.11.0(8.12.1)
Admin-Adapter V6.1.11
![image](https://user-images.githubusercontent.com/51095725/177930684-a090a62a-8d51-40dc-a87a-447e55b0a775.png)
Läuft die Installation sauber durch und die Daten werden regelmäßig heruntergeladen.

Dankeschön!

**Comment by raschy** [comment]
@fr00sch Ja das freut mich. Die Warnungen kommen daher, dass das Repository noch nicht auf npm ist. Kommt aber auch noch. Viel Spaß.
