### ISSUE TITLE
Feature Request: extract total production

### ISSUE THREAD

**Issue by snoerfsnoerf** [raschy/ioBroker.solarmanpv#55]
Thanks for the plugin - works perfect. 

Is it possible to extend the feature by extracting additional information provided by the API? especially the "Total Production" would be a valuable field for me.

**Comment by Baenker** [comment]
Verstehe leider nicht genau was Du meinst?  Es gibt doch z. B. solarmanpv.0.xxxxxx.Et_ge0 das ist doch Total Production?

**Comment by raschy** [comment]
In the meantime, my horizon has also expanded somewhat and I can now not only collect relevant data from the inverters, but also virtually all values from batteries and collectors. This will be reflected in the upcoming version 0.3.1.

**Comment by raschy** [comment]
No new findings or requirements
