### ISSUE TITLE
Keine Verbindung trotz Dateneingabe

### ISSUE THREAD

**Issue by Peterlustig123456** [raschy/ioBroker.solarmanpv#59]
Hallo zusammen, 

die Daten habe ich ohne Probleme von SOLARMAN bekommen. 

1.Zeile ID 2.Zeile Geheimniss

leider keine Daten bekommen, gibt es hier weiter etwas zu beachten? 

Danke im Voraus!

**Comment by raschy** [comment]
Hallo Peterlustig123456, wie kommst du auf 1.Zeile / 2.Zeile? Bei mir sieht das UI so aus und sollte mit den richtigen Daten von dir auch funktionieren.
![Instanz_SolarmanPV_Muster](https://user-images.githubusercontent.com/75622810/224536311-e1703439-2b64-4416-b5ec-2edb537d7b32.png)

**Comment by Peterlustig123456** [comment]
Hallo raschy,

ja richtig ist nebeneinander, jedoch bekomme ich in den Objekten keinerlei Daten angezeigt.
Bin da noch recht neu in der Materie, bitte um Nachsicht.

APP ID sowie APP Secret PW und Mail ist eingetragen

Gruß

**Comment by raschy** [comment]
Evtl. blöde Frage: scheint die Sonne? Was steht im Protokoll unter 'solarmanpv.0' ?

**Comment by Peterlustig123456** [comment]
sonne ist ausreichend,WR läuft.

anbei mal das Protokoll
[image: Bildschirmfoto 2023-03-12 um 14.18.40.png]


Am So., 12. März 2023 um 14:12 Uhr schrieb raschy ***@***.***

**Comment by raschy** [comment]
Leider kein Foto

**Comment by Peterlustig123456** [comment]
Am So., 12. März 2023 um 14:19 Uhr schrieb Christian Lauer <
***@***.***>:

**Comment by Peterlustig123456** [comment]
hoffe hat jetzt geklappt

Am So., 12. März 2023 um 14:28 Uhr schrieb Christian Lauer <
***@***.***>:

**Comment by raschy** [comment]
Ich vermute mal, dass das mit dem Hochladen des Fotos nicht so ganz klappt. Das Foto in den unteren Bereich "Attach files by dragging ... " reinziehen. Oder besser noch, das Protokoll als Text in CodeTags.

**Comment by Peterlustig123456** [comment]
![Bildschirmfoto 2023-03-12 um 14 18 40](https://user-images.githubusercontent.com/127654628/224548377-4d310177-6899-4eb8-9f95-fdbf1a0aa29d.png)

**Comment by raschy** [comment]
Ok. Jetzt kann ich was sehen. Was zeigt denn die Solarman App an?  Offensichtlich sind deine Credentials ok, aber der China-Server antwortet nicht (richtig).

**Comment by Peterlustig123456** [comment]
Die App funktioniert regulär, kann ich in der App zusätzlich etwas prüfen?

**Comment by raschy** [comment]
Dann wird es für mich etwas schwierig. Traust du mir, dann schick mir deine Zugangsdaten per Mail an raschy@gmx.de. Dann kann ich etwas tiefer nachschauen.

**Comment by FabulousGee** [comment]
Habe leider das selbe Problem

![image](https://user-images.githubusercontent.com/30511025/227177875-88cd5c04-a13f-4005-ad8b-d0eac1677075.png)

**Comment by raschy** [comment]
Das Problem ist wahrscheinlich ähnlich. Zum einen sieht es so aus, als ob der Adapter mehrfach laufen würde "solarmanpv.0 already running". 
Für den Fehler "[initializeStation] error: undefined" würde ich die Cloud verantwortlich machen. Meiner Beobachtung nach ist die Solarman-Plattform derzeit sehr instabil. Daher schlage ich vor, die nächsten Tage abzuwarten.

**Comment by FabulousGee** [comment]
Der ECONNABORTED und already running kommen immer dann, wenn man bei laufendem Adapter Werte ändert und auf Speichern klickt. Scheint so, als würde der Adapter dann nochmal angestartet werden, ohne dass er vorher gestoppt wurde.

Gibts denn irgendwo die Möglichkeit, manuell ein Debug-Flag zu setzen? Dann würde ich in der Richtung mal forschen.
Oder ne API-Dokumentation von Solarman - wäre auch schon hilfreich :-)

Ansonsten habe ich dir auch mal Zugangsdaten zukommen lassen zum Testen...

**Comment by Pixelshading** [comment]
![grafik](https://user-images.githubusercontent.com/37512022/227263734-6bb702cc-6b90-48ab-970f-8029a0e6de6c.png)

Jup hab auch das selbe problem

**Comment by raschy** [comment]
@Peterlustig123456 @Pixelshading Anhand der Daten von FaboulosGee habe ich feststellen müssen, dass mit den angegebenen Credentials von der Solarman-Cloud kein Token abgeholt werden konnte. Daher habe ich den Vorschlag gemacht, beim Solarman-Support anzufragen, ob da etwas schief läuft. Eine Anfrage dazu könnte so lauten: "I am a user of the Solarman app and have also been retrieving data via the Api using Api ID and Api Secrets for over half a year. Since yesterday, I no longer receive a valid token or an error message "could not retrieve token". Do you have an explanation for this or how can we remedy the situation?"

**Comment by Peterlustig123456** [comment]
@raschy vielen Dank es funktioniert endlich !

**Comment by raschy** [comment]
@Peterlustig123456 Darf ich noch für die anderen User fragen: Hast du den Support angemailt und was ist danach passiert? Neue Credentials oder nur ein "Erledigt" aus China?

**Comment by Peterlustig123456** [comment]
Weder noch, hatte die Zugangsdaten nochmals eingegeben, dann einen Tag gewartet. Jetzt passt es.

**Comment by FabulousGee** [comment]
Bei mir hat sich soeben herausgestellt, dass die API-ID wohl falsch übermittelt wurde. Der Herr vom Support hat hinten eine Zahl zu wenig übermittelt :-) Bei mir geht es nun auch...

War wohl eine Kombination aus API-Problemen und (bei mir) Credentials.
