### ISSUE TITLE
[initializeStation] error: ECONNABORTED

### ISSUE THREAD

**Issue by Fontheweg** [raschy/ioBroker.solarmanpv#60]
I'm basicly using this adapter since 2 month without issues.
But since the last update to v0.3.1 I got a warning many times a day :: [initializeStation] error: ECONNABORTED

Today so far:
solarmanpv.0 | 2023-03-15 14:00:06.494 | warn | [initializeInverter] error: ECONNABORTED
solarmanpv.0 | 2023-03-15 13:00:05.907 | warn | [initializeStation] error: ECONNABORTED
solarmanpv.0 | 2023-03-15 12:15:05.419 | warn | [initializeStation] error: ECONNABORTED
solarmanpv.0 | 2023-03-15 12:05:06.581 | warn | [initializeStation] error: ECONNABORTED
solarmanpv.0 | 2023-03-15 12:00:07.034 | warn | [initializeStation] error: ECONNABORTED
solarmanpv.0 | 2023-03-15 09:10:10.072 | warn | [initializeStation] error: ECONNABORTED

I think it is not realy an issue with the adapter, because the other times it works fine ... but is it possible to set the timeout higher - with a configfield for example ? Eventualy this can solve the problem ?!

**Comment by raschy** [comment]
I don't think a timeout extension is helpful here. My observation is that the Solarman platform is currently very unstable. Therefore, I suggest waiting for the next few days. I refrain from setting by the user.

**Comment by Fontheweg** [comment]
Okay, I'll standby. Thank you for the quick response!

**Comment by raschy** [comment]
Since no further findings have accumulated here, I close this issue.
