### ISSUE TITLE
Blacklisting does not work

### ISSUE THREAD

**Issue by unstressable** [raschy/ioBroker.solarmanpv#68]
Could anyone please explain the blacklisting feature?

I got 2 different PV projects over the same account.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/50423935/233453542-23f9163b-9f3b-4772-bff3-b6eca469bb1e.png">

I want to see them respectively alone on two different ioBroker installations.

When I use the phrase "1918xxxx" for example nothing changes.

**Comment by raschy** [comment]
The blacklist refers to individual data points below an object tree. In this case, both folders are supplied by one account and cannot be split.
Hiding a folder if it is not of interest is planned for a later version.

**Comment by simplest-circuits** [comment]
Can you share how to use the "blacklist" in general, please?

**Comment by raschy** [comment]
The 'Blacklist' is designed to hide individual data points that are not needed. 
To do this, enter the terms here separated by commas and then delete the data point manually.
![Blacklist](https://github.com/raschy/ioBroker.solarmanpv/assets/75622810/a21f56be-6e6b-4e21-8043-2929b95609a2)
