### ISSUE TITLE
instance system.adapter.solarmanpv.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by m-O-rpheus** [raschy/ioBroker.solarmanpv#69]
Hello,

I was able to install the adapter with no problems. But no objects are created for me. I.e. the object tree is empty.

Instead I get the following error message in the console
instance system.adapter.solarmanpv.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
Everything seems to be working fine for all other users. What's wrong with me?

Raspberry Pi4
NodeJS. v12.22.12
NPM: 6.14.16
js-controller 4.0.23

Thanks alot

**Comment by raschy** [comment]
The adapter does not work with NodeJS 12.x. This version is discontinued! Please upgrade the system to NodeJS version 18.x, then the adapter should work.
