### ISSUE TITLE
Moduls not updated

### ISSUE THREAD

**Issue by sokrates-sith** [raschy/ioBroker.solarmanpv#79]
Since the last update the modules are not updated anymore.
I have v0.4.2

![image](https://github.com/raschy/ioBroker.solarmanpv/assets/76497549/1570d7f2-2642-4815-b99b-5485d60e82fa)

only the whole power of the system is shown correct

**Comment by raschy** [comment]
Are the modules for evaluation also ticked on the 'System modules' tab?
![Systemmodule](https://github.com/raschy/ioBroker.solarmanpv/assets/75622810/04452241-b1e7-4cc1-b0b8-023f40427c68)

**Comment by sokrates-sith** [comment]
ah, nope, the tab is empty. anything i can do to load them?
![image](https://github.com/raschy/ioBroker.solarmanpv/assets/76497549/f733b5c2-e751-4b38-bfac-488146a926d6)

**Comment by Ilovegym66** [comment]
hier auch so, es werden keine Untermodule angezeigt..

**Comment by raschy** [comment]
Besteht die Möglichkeit, den Adapter mal komplett zu deinstallieren und dann wieder neu zu installieren?

**Comment by sokrates-sith** [comment]
ok, das hat geholfen. ich sehe nun die module in "systemmodule" und aktuell werden die werte wieder aktualisiert.

**Comment by raschy** [comment]
Danke für die Rückmeldung. Freut mich, dass es wieder funktioniert.

**Comment by sokrates-sith** [comment]
danke auch für die schnelle hilfe
