### ISSUE TITLE
Systemmodule in Instanzeinstellungen not shown from second inverter

### ISSUE THREAD

**Issue by sgersing73** [raschy/ioBroker.solarmanpv#80]
**Describe the bug**  
Untermodule from second Inverter not shown and selectable

**To Reproduce**  
1. Go to 'Instanzeinstellungen: solarmanpv.0v0.4.2'
2. Click on 'Systemmodule'
3. See error

**Versions:**  
 - Adapter version: <v0.4.2>
 - Node version: <v16.18.1>

**Comment by sgersing73** [comment]
Adapter reinstalled

**Comment by raschy** [comment]
Problem is fixed in Version 0.4.3
