### ISSUE TITLE
DP wechselt permanent von "true" auf "(null)"

### ISSUE THREAD

**Issue by Kusi-Schweiz** [raschy/ioBroker.solarmanpv#97]
Der Datenpunkt "system.adapter.solarmanpv.0.connected" wechselt vor jedem "CRON-Start" von "true" auf "leer", dann kurz 
"(null)", danach wieder auf "true".
Kann es geändert werden, dass dieser DP permanent auf "true" bleibt?

![image](https://github.com/raschy/ioBroker.solarmanpv/assets/71840093/9132f974-8a98-498a-a82c-478210e66ee5)
![image](https://github.com/raschy/ioBroker.solarmanpv/assets/71840093/dc6252a2-566f-4e80-b781-cf33a18c4cf8)
![image](https://github.com/raschy/ioBroker.solarmanpv/assets/71840093/d9d7cddb-844f-4bcf-8323-27498d11334a)

Die History vom DP "system.adapter.solarmanpv.0.connected":
![image](https://github.com/raschy/ioBroker.solarmanpv/assets/71840093/f80150fb-6510-4f96-8fd9-16521cb028d4)

Hintergrund ist der, dass ich  auf "IDs vom Selektor (system.adapter.*.0.connected)" triggere, um eine Meldung zu erhalten, wenn ein Dienst/Gerät nicht mehr erreichbar ist, respektive die Verbindung wieder hergestellt wurde.

Das Blockly:
![image](https://github.com/raschy/ioBroker.solarmanpv/assets/71840093/7dc19569-7360-4a33-be11-4f5608bccc59)

**Comment by raschy** [comment]
Der Adapter ist ein 'scheduled Adapter', der während der inaktiven Zeit nicht läuft. Dieses 'connected' prüft also nur die Verbindung vom Admin (js-controller) zum Adapter und wird also ständig zwischen (null) und true wechseln. Um das oben beschriebene Vorhaben über diesen Weg zu lösen, müsste ich den Adapter als Daemon umschreiben - das ist aber nicht geplant.

**Comment by Kusi-Schweiz** [comment]
Danke für die Information. Dann werde ich diesen Abdapter bei der "connected"-Abfrage vorübergehend herausnehmen mit einem "falls"-Block.

Könnte denn programmiert werden, dass dieser Datenpunkt nur "true" und "false" hat?

**Comment by raschy** [comment]
Dieser Datenpunkt wird ja vom Admin gesetzt und erfüllt so seine Aufgabe richtig. Änderung wäre nur, dass ich den Adapter komplett umschreibe auf Daemon. Dann ist der Datenpunkt - wenn der Adapter läuft - dauernd true.
